// Code generated by ogen, DO NOT EDIT.

package client

import (
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func encodeSiteverifyRequest(
	req *SiteverifyForm,
	r *http.Request,
) error {
	const contentType = "application/x-www-form-urlencoded"
	request := req

	q := uri.NewFormEncoder(map[string]string{})
	{
		// Encode "secret" form field.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "secret",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}
		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(request.Secret))
		}); err != nil {
			return errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "response" form field.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "response",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}
		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(request.Response))
		}); err != nil {
			return errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "remoteip" form field.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "remoteip",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}
		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(request.Remoteip))
		}); err != nil {
			return errors.Wrap(err, "encode query")
		}
	}
	encoded := q.Values().Encode()
	ht.SetBody(r, strings.NewReader(encoded), contentType)
	return nil
}
