// Code generated by queryhelpergen; DO NOT EDIT.
// Source: crud.go

package example

import (
	query "github.com/theater-improrama/go-utils/query"
	time "time"
)

var Filter _Filter

type _Filter struct {
	query.FilterBase[FilterBuilder]
}

func (_Filter) CreatedAfter(t time.Time) query.FilterPredicate[FilterBuilder] {
	return func(b FilterBuilder) FilterBuilder {
		return b.CreatedAfter(t)
	}
}
func (_Filter) NameEq(name string) query.FilterPredicate[FilterBuilder] {
	return func(b FilterBuilder) FilterBuilder {
		return b.NameEq(name)
	}
}

var OrderBy _OrderBy

type _OrderBy struct{}

func (_OrderBy) CreatedAt(o query.Order) query.OrderByFunc[OrderByBuilder] {
	return func(b OrderByBuilder) OrderByBuilder {
		return b.CreatedAt(o)
	}
}
func WithPagination(offset, limit int) query.Option[FilterBuilder, OrderByBuilder] {
	return func(b query.Builder[FilterBuilder, OrderByBuilder]) {
		b.Paginate(offset, limit)
	}
}
func WithFilter(fn query.FilterPredicate[FilterBuilder]) query.Option[FilterBuilder, OrderByBuilder] {
	return func(b query.Builder[FilterBuilder, OrderByBuilder]) {
		b.Filter(fn)
	}
}
func WithOrderBy(fns ...query.OrderByFunc[OrderByBuilder]) query.Option[FilterBuilder, OrderByBuilder] {
	return func(b query.Builder[FilterBuilder, OrderByBuilder]) {
		b.OrderBy(fns...)
	}
}
