// Code generated by queryhelpergen; DO NOT EDIT.
// Source: crud.go

package example

import (
	query "github.com/theater-improrama/go-utils/query"
	time "time"
)

// FilterBuilder is the fluent builder interface for constructing filters.
// Implementations are provided by database adapters.
type FilterBuilder interface {
	query.FilterBuilderLogic[FilterBuilder]
	CreatedAfter(t time.Time) FilterBuilder
	NameEq(name string) FilterBuilder
}

// FILTER provides helper methods for constructing filter predicates.
var FILTER Filter

type Filter struct {
	query.FilterBase[FilterBuilder]
}

func (Filter) CreatedAfter(t time.Time) query.FilterPredicate[FilterBuilder] {
	return func(b FilterBuilder) FilterBuilder {
		return b.CreatedAfter(t)
	}
}

func (Filter) NameEq(name string) query.FilterPredicate[FilterBuilder] {
	return func(b FilterBuilder) FilterBuilder {
		return b.NameEq(name)
	}
}

// OrderByBuilder is the fluent builder interface for constructing order clauses.
// Implementations are provided by database adapters.
type OrderByBuilder interface {
	CreatedAt(order query.Order) OrderByBuilder
}

// ORDER_BY provides helper methods for constructing order clauses.
var ORDER_BY OrderBy

type OrderBy struct{}

func (OrderBy) CreatedAt(order query.Order) query.OrderByFunc[OrderByBuilder] {
	return func(b OrderByBuilder) OrderByBuilder {
		return b.CreatedAt(order)
	}
}

func WithPagination(offset, limit int) query.Option[FilterBuilder, OrderByBuilder] {
	return func(b query.Builder[FilterBuilder, OrderByBuilder]) {
		b.Paginate(offset, limit)
	}
}

func WithFilter(fn query.FilterPredicate[FilterBuilder]) query.Option[FilterBuilder, OrderByBuilder] {
	return func(b query.Builder[FilterBuilder, OrderByBuilder]) {
		b.Filter(fn)
	}
}

func WithOrderBy(fns ...query.OrderByFunc[OrderByBuilder]) query.Option[FilterBuilder, OrderByBuilder] {
	return func(b query.Builder[FilterBuilder, OrderByBuilder]) {
		b.OrderBy(fns...)
	}
}
