name: "Release"
run-name: "Release"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1
        name: Create GitHub Release
        with:
          body: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}