name: "Test repository"
run-name: "Test repository"
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25.1"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Dependencies
        run: go mod download
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Test
        run: ginkgo -r --cover ./...